### PR TITLE
[Feature] Versioned dynamic nodes

### PR DESCRIPTION
**Pull request by jpfeuffer**
First steps towards dynamic versioning of (dynamic) GKN plugins:
- Multiple versions of the same plugin can be installed now and are registered and handled through a new extension point
- Only the nodes of the newest version of the plugin is visible in the node repo as the rest is deprecated.
- If an old node is in a workflow the old version will be used
- Automatic installation mechanism should be working for missing versions of a plugin (to be confirmed)
- Updated the resource lookup mechanism of both the versioned and unversioned dynamicnodesetfactories (e.g. support binaries in platform-specific fragments)

The use of this mechanism is probably not yet stable. For now, stick to static generation in production.
Updates to come. We will test it on a beta update site.

### CODE REVIEW

**Review by AlexanderFillbrunn — APPROVED** [review]
Seems good to me. A beta update site with dynamically generated nodes is a good idea. The plugin could also contain the old, statically generated nodes, but marked as deprecated.

**Comment by jpfeuffer** [comment]
Ok. Let's try to rebuild. There was something wrong with the version variables.

**Comment by jpfeuffer** [comment]
rebuild

**Comment by jpfeuffer** [comment]
Weird error: Maybe I used nodes with a too old Java version.
rebuild

**Comment by jpfeuffer** [comment]
Wow does the rebuild keyword have to be in one line? Worst plugin ever..

**Comment by jpfeuffer** [comment]
Yes. Works on 16.04. Probably the Java/Eclipse version. Still had small error in RMAP. rebuild

**Comment by jpfeuffer** [comment]
Great. Compiles with both recent KNIME versions. Will merge.

**Pull request merged**
