### PR TITLE
Changes to remove deprecated code as of KNIME 3.0

### PR DESCRIPTION
**Pull request by chahuistle**

### CODE REVIEW

**Comment by jpfeuffer** [comment]
What's the status here?

**Comment by chahuistle** [comment]
I think all needed changes to remove deprecated code have been made.

**Comment by jpfeuffer** [comment]
Ok. So is it ready to merge? Or do you mean these changes have been merged in other PRs already?
You are the boss here ;)

**Comment by chahuistle** [comment]
Sorry... It's ready to merge... I think I already made a pull request for
it.

**Comment by jpfeuffer** [comment]
The one we are currenlty commenting in?

**Comment by chahuistle** [comment]
Ah... I was using the "Reply to this email" feature directly... Yeah, this
one right here!

**Comment by jpfeuffer** [comment]
Changes merged via the 3.1 branch

**Pull request closed without merging**
