### PR TITLE
Concatenation happens ONLY for docker-based nodes (this broke OpenMS)

### PR DESCRIPTION
**Pull request by chahuistle**
@jpfeuffer Made the concatenation mandatory only for docker-based nodes.

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Looks good. Could you already test it a bit?

**Comment by jpfeuffer** [comment]
@b-schubert What do you think about this? Does it crash ImmunoNodes?

**Comment by jpfeuffer** [comment]
Merge because blocker.

**Comment by b-schubert** [comment]
Sorry guys, I'm still struggling with my wisdom tooth OP. I dont think I will be able to test this in the next couple of days.

**Pull request merged**
